services:
  api:
    container_name: image-router-api
    image: node:20-bookworm
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c '
        apt-get update && apt-get install -y tini &&
        npm install &&
        exec tini -- npm start
      '
    volumes:
      - .:/app
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=production
    networks:
      - wasp-network

networks:
  wasp-network:
    name: wasp-network