version: '3.8'

services:
  api:
    container_name: image-router-api
    image: node:20-bookworm
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:${PORT}:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm start"
    restart: unless-stopped 